name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  test-lint-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make install
    # - name: Check Lint
    #   run: make lint
    - name: Check Format
      run: make format ARGS=--check
    - name: Run Tests
      run: make test
    - name: Build Stars
      run: make stars
